// <auto-generated />
using System;
using API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FolhaPagamento.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20240510144736_AjustaIdString")]
    partial class AjustaIdString
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("API.Models.Folha", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ano")
                        .HasColumnType("INTEGER");

                    b.Property<string>("funcionarioId")
                        .HasColumnType("TEXT");

                    b.Property<float?>("impostoFgts")
                        .HasColumnType("REAL");

                    b.Property<float?>("impostoInss")
                        .HasColumnType("REAL");

                    b.Property<float?>("impostoIrrf")
                        .HasColumnType("REAL");

                    b.Property<int?>("mes")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<float?>("salarioBruto")
                        .HasColumnType("REAL");

                    b.Property<float?>("salarioLiquido")
                        .HasColumnType("REAL");

                    b.Property<float?>("valor")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("funcionarioId")
                        .IsUnique();

                    b.ToTable("TabelaFolha");
                });

            modelBuilder.Entity("API.Models.Funcionario", b =>
                {
                    b.Property<string>("funcionarioId")
                        .HasColumnType("TEXT");

                    b.Property<string>("cpf")
                        .HasColumnType("TEXT");

                    b.Property<string>("nome")
                        .HasColumnType("TEXT");

                    b.HasKey("funcionarioId");

                    b.ToTable("TabelaFuncionario");
                });

            modelBuilder.Entity("API.Models.Folha", b =>
                {
                    b.HasOne("API.Models.Funcionario", null)
                        .WithOne("funcionario")
                        .HasForeignKey("API.Models.Folha", "funcionarioId");
                });

            modelBuilder.Entity("API.Models.Funcionario", b =>
                {
                    b.Navigation("funcionario");
                });
#pragma warning restore 612, 618
        }
    }
}
